package app_escuela;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import app_escuela.Carrera;
import app_escuela.CarreraDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;



public class FrmAlumno extends javax.swing.JFrame {
     // ==== VARIABLES DE APOYO ====

    private AlumnoDAO alumnoDAO = new AlumnoDAO();
    private CarreraDAO carreraDAO = new CarreraDAO();
    private DefaultTableModel modelo;

    private List<Carrera> listaCarreras = new ArrayList<>(); // <--- NUEVO
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlumno.class.getName());

    /**
     * Creates new form FrmAlumno
     */
    public FrmAlumno() {
        initComponents();
        cargarCarreras();
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent e) {
            char c = e.getKeyChar();

            // Si NO es dígito, no deja escribir
            if (!Character.isDigit(c)) {
                e.consume();
                return;
            }

            // Si ya hay 5 caracteres, no deja escribir más
            if (txtMatricula.getText().length() >= 5) {
                e.consume();
            }
        }
    });
        // tomar el modelo actual de la tabla
    modelo = (DefaultTableModel) tablaAlumnos.getModel();
    cargarTabla();// llenarla al iniciar 
    
    
    }
    
    private void cargarCarreras() {
    cmbCarrera.removeAllItems(); // Limpia el combo

    try {
        Connection cn = Conexion.getConnection();
        String sql = "SELECT nombre_car FROM carrera ORDER BY nombre_car";
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            cmbCarrera.addItem(rs.getString("nombre_car"));
        }

        rs.close();
        ps.close();
        cn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar carreras: " + e.getMessage());
    }
}

    
        private void cargarTabla() {
        // Limpia la tabla
        modelo.setRowCount(0);

        // Pide la lista de alumnos al DAO
        List<Alumno> lista = alumnoDAO.listar();

        // Agrega cada alumno como fila
        for (Alumno a : lista) {
            Object[] fila = new Object[]{
                a.getMatricula(),
                a.getNombre_s(),
                a.getAp_pat(),
                a.getAp_mat(),
                a.getSemestre(),
                a.getCarrera()
            };
            modelo.addRow(fila);
        }
    }
            private void limpiarCampos() {
        txtMatricula.setText("");
        txtNombre.setText("");
        txtApPat.setText("");
        txtApMat.setText("");
        txtSemestre.setText("");
        cmbCarrera.setSelectedIndex(-1);
        tablaAlumnos.clearSelection();
        
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApPat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jLabel5.setText("Matrícula:");
        jPanel1.add(jLabel5);

        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);
        jPanel1.add(txtMatricula);

        jLabel8.setText("Nombre:");
        jPanel1.add(jLabel8);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        jPanel1.add(txtNombre);

        jLabel9.setText("Apellido Paterno:");
        jPanel1.add(jLabel9);

        txtApPat.addActionListener(this::txtApPatActionPerformed);
        jPanel1.add(txtApPat);

        jLabel3.setText("Apellido Materno:");
        jPanel1.add(jLabel3);

        txtApMat.addActionListener(this::txtApMatActionPerformed);
        jPanel1.add(txtApMat);

        jLabel4.setText("Semestre:");
        jPanel1.add(jLabel4);

        txtSemestre.addActionListener(this::txtSemestreActionPerformed);
        jPanel1.add(txtSemestre);

        jLabel10.setText("Carrera:");
        jPanel1.add(jLabel10);

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCarrera.addActionListener(this::cmbCarreraActionPerformed);
        jPanel1.add(cmbCarrera);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(429, 429, 429))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nombre", "Ap. Pat", "Ap. Mat", "Semestre", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumnos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPatActionPerformed

    private void txtSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestreActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtApMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApMatActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
            limpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
        String matStr = txtMatricula.getText().trim();
        if (matStr.length() != 5) {
            JOptionPane.showMessageDialog(this, "La matrícula debe tener exactamente 5 dígitos");
            return;
        }

        int matricula = Integer.parseInt(matStr);
        String nombre = txtNombre.getText().trim();
        String apPat  = txtApPat.getText().trim();
        String apMat  = txtApMat.getText().trim();
        int semestre  = Integer.parseInt(txtSemestre.getText().trim());
        
        String carrera = (String) cmbCarrera.getSelectedItem();
        if (carrera == null || carrera.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona una carrera");
            return;
        }

        Alumno a = new Alumno();
        a.setMatricula(matricula);
        a.setNombre_s(nombre);
        a.setAp_pat(apPat);
        a.setAp_mat(apMat);
        a.setSemestre(semestre);
        a.setCarrera(carrera);
        

        if (alumnoDAO.insertar(a)) {
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente");
            cargarTabla();
            limpiarCampos();
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Matrícula y semestre deben ser números");
    }

          
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     if (txtMatricula.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un alumno de la tabla primero");
        return;
    }
     String matStr = txtMatricula.getText().trim();
    if (matStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un alumno de la tabla primero");
        return;
    }
    if (matStr.length() != 5) {
        JOptionPane.showMessageDialog(this, "La matrícula debe tener exactamente 5 dígitos");
        return;
    }

    try {
        int matricula = Integer.parseInt(txtMatricula.getText().trim());
        String nombre = txtNombre.getText().trim();
        String apPat = txtApPat.getText().trim();
        String apMat = txtApMat.getText().trim();
        int semestre = Integer.parseInt(txtSemestre.getText().trim());
        String carrera = (String) cmbCarrera.getSelectedItem();
    if (carrera == null || carrera.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Selecciona una carrera");
    return;
}

Alumno a = new Alumno();
a.setMatricula(matricula);
a.setNombre_s(nombre);
a.setAp_pat(apPat);
a.setAp_mat(apMat);
a.setSemestre(semestre);
a.setCarrera(carrera);

      if (alumnoDAO.actualizar(a)) {
    JOptionPane.showMessageDialog(this, "Alumno actualizado correctamente");
    cargarTabla();
    limpiarCampos();

  }
      }catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this,
                "Valores numéricos inválidos (matrícula o semestre)");
    
   
   
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if (txtMatricula.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un alumno de la tabla primero");
        return;
    }

    int resp = JOptionPane.showConfirmDialog(this,
            "¿Seguro que deseas eliminar este alumno?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (resp == JOptionPane.YES_OPTION) {
        int matricula = Integer.parseInt(txtMatricula.getText().trim());
        if (alumnoDAO.eliminar(matricula)) {
            JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente");
            cargarTabla();
            limpiarCampos();
        }
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
         int fila = tablaAlumnos.getSelectedRow();
    if (fila >= 0) {
        txtMatricula.setText(tablaAlumnos.getValueAt(fila, 0).toString());
        txtNombre.setText(tablaAlumnos.getValueAt(fila, 1).toString());
        txtApPat.setText(tablaAlumnos.getValueAt(fila, 2).toString());
        txtApMat.setText(tablaAlumnos.getValueAt(fila, 3).toString());
        txtSemestre.setText(tablaAlumnos.getValueAt(fila, 4).toString());
       String carrera = tablaAlumnos.getValueAt(fila, 5).toString();
        cmbCarrera.setSelectedItem(carrera);
    }
    }//GEN-LAST:event_tablaAlumnosMouseClicked

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAlumno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
