/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_escuela;

/**
 *
 * @author edson
 */
public class FrmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null); // centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegAlumno = new javax.swing.JButton();
        btnRegProfesor = new javax.swing.JButton();
        btnVerAlumnos = new javax.swing.JButton();
        btnVerProfesores = new javax.swing.JButton();
        btnVerCarrerasMaterias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela UAdeO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Escuela UAdeO");

        btnRegAlumno.setText("Registrar alumno");
        btnRegAlumno.addActionListener(this::btnRegAlumnoActionPerformed);

        btnRegProfesor.setText("Registrar profesor");
        btnRegProfesor.addActionListener(this::btnRegProfesorActionPerformed);

        btnVerAlumnos.setText("Mirar alumnos");
        btnVerAlumnos.addActionListener(this::btnVerAlumnosActionPerformed);

        btnVerProfesores.setText("Mirar profesores");
        btnVerProfesores.addActionListener(this::btnVerProfesoresActionPerformed);

        btnVerCarrerasMaterias.setText("Mirar carreras y materias");
        btnVerCarrerasMaterias.addActionListener(this::btnVerCarrerasMateriasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnRegAlumno)
                .addGap(26, 26, 26)
                .addComponent(btnRegProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnVerAlumnos)
                .addGap(44, 44, 44)
                .addComponent(btnVerProfesores)
                .addGap(47, 47, 47)
                .addComponent(btnVerCarrerasMaterias)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerAlumnos)
                    .addComponent(btnVerProfesores)
                    .addComponent(btnVerCarrerasMaterias)
                    .addComponent(btnRegProfesor)
                    .addComponent(btnRegAlumno))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAlumnoActionPerformed
         FrmAlumno frm = new FrmAlumno();
    frm.setVisible(true);
    }//GEN-LAST:event_btnRegAlumnoActionPerformed

    private void btnVerAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnosActionPerformed
         FrmAlumno frm = new FrmAlumno();
    frm.setVisible(true);
    }//GEN-LAST:event_btnVerAlumnosActionPerformed

    private void btnRegProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProfesorActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pantalla de registrar profesor (pendiente)");
    }//GEN-LAST:event_btnRegProfesorActionPerformed

    private void btnVerProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProfesoresActionPerformed
       javax.swing.JOptionPane.showMessageDialog(this,
            "Pantalla de ver profesores (pendiente)");
    }//GEN-LAST:event_btnVerProfesoresActionPerformed

    private void btnVerCarrerasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarrerasMateriasActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pantalla de carreras y materias (pendiente)");
    }//GEN-LAST:event_btnVerCarrerasMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegAlumno;
    private javax.swing.JButton btnRegProfesor;
    private javax.swing.JButton btnVerAlumnos;
    private javax.swing.JButton btnVerCarrerasMaterias;
    private javax.swing.JButton btnVerProfesores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
